// Generated by hand. Run `supabase gen types typescript --linked` to regenerate.
export type Json = string | number | boolean | null | { [k: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" };
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          locale: "en" | "ms";
          referral_code: string;
          referred_by: string | null;
          created_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["profiles"]["Row"]> & { id: string; email: string };
        Update: Partial<Database["public"]["Tables"]["profiles"]["Row"]>;
        Relationships: [];
      };
      credits: {
        Row: {
          user_id: string;
          balance: number;
          lifetime_used: number;
          monthly_quota: number;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["credits"]["Row"]> & { user_id: string };
        Update: Partial<Database["public"]["Tables"]["credits"]["Row"]>;
        Relationships: [];
      };
      subscriptions: {
        Row: {
          id: string;
          user_id: string;
          chip_customer_id: string | null;
          chip_subscription_id: string | null;
          plan: "monthly" | "annual";
          status: "active" | "past_due" | "cancelled" | "paused";
          current_period_end: string | null;
          cancel_at_period_end: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["subscriptions"]["Row"]> & { user_id: string; plan: "monthly" | "annual" };
        Update: Partial<Database["public"]["Tables"]["subscriptions"]["Row"]>;
        Relationships: [];
      };
      generations: {
        Row: {
          id: string;
          user_id: string | null;
          anon_fingerprint: string | null;
          mode: "resume" | "cover_letter";
          job_title: string | null;
          company: string | null;
          jd_hash: string | null;
          payload: Json;
          ats_score: number | null;
          created_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["generations"]["Row"]> & { mode: "resume" | "cover_letter"; payload: Json };
        Update: Partial<Database["public"]["Tables"]["generations"]["Row"]>;
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          user_id: string | null;
          chip_purchase_id: string;
          amount: number;
          currency: string;
          status: string;
          kind: "topup" | "subscription" | "renewal";
          credits_granted: number;
          created_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["payments"]["Row"]> & { chip_purchase_id: string; amount: number; status: string; kind: "topup" | "subscription" | "renewal" };
        Update: Partial<Database["public"]["Tables"]["payments"]["Row"]>;
        Relationships: [];
      };
      referrals: {
        Row: {
          referee_id: string;
          referrer_id: string;
          status: "pending" | "credited" | "expired";
          credited_at: string | null;
          created_at: string;
        };
        Insert: Partial<Database["public"]["Tables"]["referrals"]["Row"]> & { referee_id: string; referrer_id: string };
        Update: Partial<Database["public"]["Tables"]["referrals"]["Row"]>;
        Relationships: [];
      };
    };
    Views: {
      my_credits: {
        Row: {
          user_id: string;
          balance: number;
          lifetime_used: number;
          monthly_quota: number;
          updated_at: string;
        };
        Relationships: [];
      };
    };
    Functions: {
      consume_credit_signed_in: { Args: Record<string, never>; Returns: number };
      refund_credit_signed_in: { Args: Record<string, never>; Returns: number };
      merge_anon_into_user: { Args: { fp: string }; Returns: number };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
